# Generated by Django 5.1.1 on 2024-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('marks', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
